config/routes.rb
Teste1::Application.routes.draw do

	resources :categorias

	resources :categorias

	resources :perfis

	devise_for :admin,
			:path => '/',
			:path_names => {
				:sign_in  => 'entrar',
				:sign_out => 'sair',
				:sign_up => 'registrar'}

	root :to => "home#index"
	
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_many :categorias, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	belongs_to :admin, :foreign_key => 'admin_id'
	#belongs_to :categoria, :foreign_key => 'categoria_id', :class_name => 'Categoria'
	has_many :categorias, :foreign_key => 'subcat_id', :class_name => 'Categoria', :dependent => :destroy

	validates_presence_of :admin_id, :message => ' deve ser preenchido!'
	validates_presence_of :descricao, :message => ' deve ser preenchida!'	
	#validates_presence_of :subcat_id, :message => ' deve ser preenchida!'
	
	validates_presence_of :admin, :message => ' inválida!'
	validates_associated :admin
	
	#validates_presence_of :categorias, :if => :testarfk? , :message => ' inválida!'
	#validates_associated :categorias
	
	def testarfk?
		if :admin_id != nil 
			true
		else
			false
		end
	end

end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
	before_filter :authenticate_admin!

  # GET /categorias
  # GET /categorias.xml
  def index
    #@categorias = Categoria.all
	#Recuperar categorias do admin logado
	@categorias = get_categorias_from_current_admin(current_admin)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categorias }
    end
  end

  # GET /categorias/1
  # GET /categorias/1.xml
  def show
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @categoria }
    end
  end

  # GET /categorias/new
  # GET /categorias/new.xml
  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @categoria }
    end
  end

  # GET /categorias/1/edit
  def edit
    @categoria = Categoria.find(params[:id])	
  end

  # POST /categorias
  # POST /categorias.xml
  def create
    @categoria = Categoria.new(params[:categoria])

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to(@categoria, :notice => 'Categoria was successfully created.') }
        format.xml  { render :xml => @categoria, :status => :created, :location => @categoria }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @categoria.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categorias/1
  # PUT /categorias/1.xml
  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to(@categoria, :notice => 'Categoria was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @categoria.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.xml
  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to(categorias_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_admin!
	
	def index
	end

end

app/controllers/perfis_controller.rb
class PerfisController < ApplicationController
	before_filter :authenticate_admin!

  # GET /perfis
  # GET /perfis.xml
  def index
    @perfis = Perfil.all
	#@perfis = get_perfis_from_current_admin(current_admin)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @perfis }
    end
  end

  # GET /perfis/1
  # GET /perfis/1.xml
  def show
    @perfil = Perfil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfis/new
  # GET /perfis/new.xml
  def new
    @perfil = Perfil.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfis/1/edit
  def edit
    @perfil = Perfil.find(params[:id])
  end

  # POST /perfis
  # POST /perfis.xml
  def create
    @perfil = Perfil.new(params[:perfil])

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to(@perfil, :notice => 'Perfil was successfully created.') }
        format.xml  { render :xml => @perfil, :status => :created, :location => @perfil }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /perfis/1
  # PUT /perfis/1.xml
  def update
    @perfil = Perfil.find(params[:id])

    respond_to do |format|
      if @perfil.update_attributes(params[:perfil])
        format.html { redirect_to(@perfil, :notice => 'Perfil was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /perfis/1
  # DELETE /perfis/1.xml
  def destroy
    @perfil = Perfil.find(params[:id])
    @perfil.destroy

    respond_to do |format|
      format.html { redirect_to(perfis_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  

	def title
		"Agregador"
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perfis_helper.rb
module PerfisHelper

	def get_perfis_from_current_admin(current_admin)
		categs = get_categorias_from_current_admin(current_admin)
		#...
		perf = Perfil.new
		return perf if current_admin == nil

		categs.each do |ct|
			perf << Perfil.find_by_categoria_id(ct.id)
		end
		
		#Esta retornando array?
		return perf
	end
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :admin_id %><br />
    <!-- <%= f.text_field :admin_id %> -->
    <div>
		<%= f.collection_select(:admin_id,
			get_array_current_admin(current_admin),
			:id, :email, {:class => 'input'} ) %>		
	</div>

  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :subcat_id %><br />
    <!--<%= f.text_field :subcat_id %>-->
	
    <div>
		<%= f.collection_select(:subcat_id,
			get_subcateg(:id),
			:id, :descricao, {:prompt => "<Raíz>"}, {:class => 'input'} ) %>		
	</div>
	
	
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/index.html.erb
<h1>Listing categorias</h1>

<table>
  <tr>
    <th>Admin</th>
    <th>Descricao</th>
    <th>Subcat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td><%= categoria.admin_id %></td>
    <td><%= categoria.id %> - <%= categoria.descricao %></td>
    <td><%= categoria.subcat_id %></td>
    <td><%= link_to 'Show', categoria %></td>
    <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Destroy', categoria, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria', new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Admin:</b>
  <%= @categoria.admin_id %>
</p>

<p>
  <b>Id:</b>
  <%= @categoria.id %>
</p>

<p>
  <b>Descricao:</b>
  <%= @categoria.descricao %>
</p>

<p>
  <b>Subcat:</b>
  <%= @categoria.subcat_id %>
</p>


<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div>
		<% if admin_signed_in? %>
			<%= link_to "Início", root_path %> | 
			<%= link_to "Categorias", categorias_path %> | 
			<%= link_to "Perfis", perfis_path %> | 
			<%= current_admin.email %>&nbsp;<%= link_to "Sair", destroy_admin_session_path %>
		<% end %>
	</div>
	<div>
		<%= yield %>
	</div>

</body>
</html>

app/views/perfis/_form.html.erb
<%= form_for(@perfil) do |f| %>
  <% if @perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% @perfil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoria_id %><br />
    <!--<%= f.text_field :categoria_id %>-->
	
    <div>
		<%= f.collection_select(:categoria_id,
			get_categorias_from_current_admin(current_admin),
			:id, :descricao, {:prompt => "Selecione..."}, {:class => 'input'} ) %>		
	</div>  
	
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perfis/edit.html.erb
<h1>Editing perfil</h1>

<%= render 'form' %>

<%= link_to 'Show', @perfil %> |
<%= link_to 'Back', perfis_path %>

app/views/perfis/index.html.erb
<h1>Listing perfis</h1>

<table>
  <tr>
    <th>Categoria</th>
    <th>Nome</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @perfis.each do |perfil| %>
  <tr>
    <td><%= perfil.categoria_id %></td>
    <td><%= perfil.nome %></td>
    <td><%= perfil.url %></td>
    <td><%= link_to 'Show', perfil %></td>
    <td><%= link_to 'Edit', edit_perfil_path(perfil) %></td>
    <td><%= link_to 'Destroy', perfil, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Perfil', new_perfil_path %>

app/views/perfis/new.html.erb
<h1>New perfil</h1>

<%= render 'form' %>

<%= link_to 'Back', perfis_path %>

app/views/perfis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Categoria:</b>
  <%= @perfil.categoria_id %>
</p>

<p>
  <b>Nome:</b>
  <%= @perfil.nome %>
</p>

<p>
  <b>Url:</b>
  <%= @perfil.url %>
</p>


<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfis_path %>